version: '3.5'

volumes:
  mongodb-data:
  redis-data:
  sni-code:

services:
  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=WMgHVNCrEtyck89D9VY5
    image: mongo
    volumes:
      - mongodb-data:/data/db
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-data:/data
  seat-navy-issue:
    container_name: seat-navy-issue
    environment:
      - GIT_URL=https://github.com/altaris/seat-navy-issue.git
      - PYTHON_MAIN=sni/sni.py
    image: altaris/pumba
    volumes:
      - sni-code:/usr/src/app/
      - ./sni.yml:/usr/src/app/sni.yml
